# Generated by Django 5.0.7 on 2024-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_active_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создаётся'), (1, 'Оплачен'), (2, 'Доставлен'), (3, 'Подписка')], default=0),
        ),
    ]
