# Generated by Django 5.0.7 on 2024-08-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_receipt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_url',
        ),
    ]
