# Generated by Django 5.0.7 on 2024-08-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_mail_flag',
            field=models.BooleanField(default=False),
        ),
    ]
